apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: jobs
  name: deployer
  labels:
    app: tester
    role: deployer
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]