apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: jobs
  name: deployer
  labels:
    app: tester
    role: deployer
subjects:
- kind: ServiceAccount
  name: deployer
  apiGroup: ""
roleRef:
  kind: Role
  name: deployer
  apiGroup: rbac.authorization.k8s.io