apiVersion: batch/v1
kind: Job
metadata:
  name: job-batch-{{ jobID }}
  labels:
    app: tester
    role: consumer
spec:
  completions: {{ completions }}
  parallelism: {{ parallelism }}
  template:
    metadata:
      name: job-consumers
      labels:
        app: tester
        role: consumer
    spec:
      ttlSecondsAfterFinished: 0 # currently not working, needs TTLAfterFinished feature gate
      containers:
          - name: job-consumer
            image: busybox:{{ tag }}
            command: ["sh", "-c", "echo Processing item && sleep 5"]
      restartPolicy: Never
