apiVersion: batch/v1
kind: Job
metadata:
  name: job-batch-{{ jobID }}
spec:
  completions: {{ completions }}
  parallelism: {{ parallelism }}
  template:
    metadata:
      name: job-workers
    spec:
      ttlSecondsAfterFinished: 0 # currently not working, needs TTLAfterFinished feature gate
      containers:
          - name: job-worker
            image: busybox:{{ tag }}
            command: ["sh", "-c", "echo Processing item && sleep 5"]
      restartPolicy: Never
